### ISSUE TITLE
Does the pipeline architecture support Windows?

### ISSUE THREAD

**Issue by davxiao** [awslabs/ami-builder-packer#14]
The pipeline is using Linux, does it support Windows from the same architecture without making significant changes?

We are looking for a set up that support both Windows and Linux

**Comment by heitorlessa** [comment]
Hey - I have not tried Windows but that would come down to making sure the
Ansible Playbook successfully runs on Windows.

If I remember correctly Packer and Ansible both support Windows with some
minor changes
