### ISSUE TITLE
Linkage to specific values in requirements.yml?

### ISSUE THREAD

**Issue by dgulli** [awslabs/ami-builder-packer#15]
Hi, 

What are the destinations within the requirements.yml file?

- src: anthcourtney.cis-amazon-linux
- src: dharrisio.aws-cloudwatch-logs-agent

should these be replace?

**Comment by dgulli** [comment]
these are also present in the playbook.yaml
Roles
   - common
    - anthcourtney.cis-amazon-linux
    # - dharrisio.aws-cloudwatch-logs-agent

**Comment by heitorlessa** [comment]
Hi @dgulli - Thanks for opening the issue. 

These are Ansible Roles that will be pulled from Galaxy, and will execute their own playbooks - You can read more in the blog post itself: https://aws.amazon.com/blogs/devops/how-to-create-an-ami-builder-with-aws-codebuild-and-hashicorp-packer-part-2/

* **anthcourtney.cis-amazon-linux**
    - This applies CIS benchmark to Amazon Linux to harden security
* **dharrisio.aws-cloudwatch-logs-agent**
    - Disabled by default, installs and ships OS logs to CloudWatch Logs

If you wanted to create your own pipeline, you could fork it, and add Ansible Roles that you'd like to use to bootstrap your AMI.

Let me know if you need more details :)

**Comment by dgulli** [comment]
hey @heitorlessa 

Great, thank you for the explanation!
