### ISSUE TITLE
SSH key not cleaned-up properly

### ISSUE THREAD

**Issue by errordeveloper** [awslabs/ami-builder-packer#7]
As `eksctl` user reported https://github.com/weaveworks/eksctl/issues/99, EKS AMIs (us-west-2/ami-73a6e20b &  us-east-1/ami-dea4d5a1) have left-over public key.

**Comment by heitorlessa** [comment]
Hi, thanks for reporting this - This needs a custom clean up action in the packer json file.

I'll try test that today and add into this demo project

**Comment by heitorlessa** [comment]
I've just tested it and this demo project does clean up the public keys for the past 2 years - https://github.com/awslabs/ami-builder-packer/blob/master/packer_cis.json#L62

I'm closing this as I believe the EKS AMI isn't built using this project
