### ISSUE TITLE
kernel time synchronization flag is not set

### ISSUE THREAD

**Issue by errordeveloper** [awslabs/ami-builder-packer#8]
It appears that Amazon Linux 2 use `crony` as NTP daemon, but according to `timedatectl status` the NTP synchronization is off:
```
[root@ip-192-168-254-114 /]# timedatectl status
      Local time: Sun 2018-07-08 11:58:28 UTC
  Universal time: Sun 2018-07-08 11:58:28 UTC
        RTC time: Sun 2018-07-08 11:58:27
       Time zone: n/a (UTC, +0000)
     NTP enabled: yes
NTP synchronized: no
 RTC in local TZ: no
      DST active: n/a
[root@ip-192-168-254-114 /]# 
```

In turns, this breaks Prometheus [`timex` metric](https://github.com/prometheus/node_exporter/blob/master/docs/TIME.md#timex-collector).

**Comment by errordeveloper** [comment]
I don't think this issue strictly belongs here, but I have no idea where else to report it.

**Comment by heitorlessa** [comment]
Hello and thank you for opening up an issue - This would be best reported in the [Amazon Linux Forum](https://forums.aws.amazon.com/forum.jspa?forumID=228).
